<?php

namespace Formation\FrontBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionStatusRepository extends EntityRepository
{
}
