imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata.yml }
    - { resource: fos_user.yml }
    - { resource: fr3d_ldap.yml }


framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - "FormationAdminBundle:Form:form_fields.html.twig"
           #- "FormationAdminBundle:Form:form_fields.html.twig"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FormationAdminBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        data_tables:
            inputs:
                - %kernel.root_dir%/../vendor/datatables/datatables/media/js/jquery.js
                - %kernel.root_dir%/../vendor/datatables/datatables/media/js/jquery.dataTables.js
                - %kernel.root_dir%/../web/bundles/adminbundle/js/custom/responsive-datatable.js
                #- %kernel.root_dir%/../web/bundles/adminbundle/css/custom/dataTables-responsive.css

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
             default:
                 mappings:
                     ApplicationSonataMediaBundle: ~
                     SonataMediaBundle: ~
                     FormationAdminBundle: ~
                     FormationUserBundle: ~
                     FormationFrontBundle: ~
                     FormationMediaBundle: ~
                     FOSUserBundle: ~
                     translatable:
                         type: annotation
                         alias: Gedmo
                         prefix: Gedmo\Translatable\Entity
                         dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                     loggable:
                         type: annotation
                         alias: Gedmo
                         prefix: Gedmo\Loggable\Entity
                         dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                     tree:
                         type: annotation
                         alias: Gedmo
                         prefix: Gedmo\Tree\Entity
                         dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


services:
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

genemu_form:
    tinymce:
        enabled: true
        theme: modern
        configs:
            entity_encoding: raw
            plugins : 'advlist autolink link image lists charmap print preview'

    date: ~
    image: ~
    select2:
        enabled: true
        configs:
            placeholder: Sélectionner
            width: off
            allowClear: false
            minimumInputLength: 0

#fos_user:
#    db_driver: orm
#    firewall_name: main
#    user_class: Formation\UserBundle\Entity\User

#fr3d_ldap:
#    driver:
#        host:         host_link.fr
##        port:         389    # Optional
##        version:        3    # I think this is specific to Windows AD - possibly 2003
##        username:     ldapproxyuser@yourADdomain    # Windows requires you to authenticate to be able to query
##        password:     whatever    # Optional
##        optReferrals: 0  #  I think this is specific to Windows AD - possibly 2003
##        useSsl:       true   # Enable SSL negotiation. Optional
##        useStartTls:  true   # Enable TLS negotiation. Optional
#    user:
#        baseDn: ou=Zephyr,ou=users,dc=ldap,dc=Zephy-web,dc=fr #cn=users, dc=yourADdomain, dc=local
##        baseDn: ou=users
#        filter: (&(ObjectClass=Person))
#        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
##           - { ldap_attr: uid,  user_method: setUsername } # Default
##           - { ldap_attr: sAMAccountName,   user_method: setName }     # Optional
#           - { ldap_attr: samaccountname,   user_method: setUsername }     # I found that these needed to be lowercase
#           - { ldap_attr: proxyaddresses, user_method: setEmailFromAD }     # to pick up email addresses...read on
##           - { ldap_attr: ...,  user_method: ... }         # Optional
##   service:
##       user_manager: fos_user.user_manager          # Overrides default user manager
##       ldap_manager: fr3d_ldap.ldap_manager.default # Overrides default ldap manager
