app:
    resource: "@AppBundle/Controller/"
    type:     annotation

formation_admin:
    resource: "@FormationAdminBundle/Ressources/config/routing.yml"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
