level:
    path:     /
    defaults: { _controller: "FormationAdminBundle:Level:index" }

level_show:
    path:     /{id}/show
    defaults: { _controller: "FormationAdminBundle:Level:show" }

level_new:
    path:     /new
    defaults: { _controller: "FormationAdminBundle:Level:new" }

level_create:
    path:     /create
    defaults: { _controller: "FormationAdminBundle:Level:create" }
    methods:  POST

level_edit:
    path:     /{id}/edit
    defaults: { _controller: "FormationAdminBundle:Level:edit" }

level_update:
    path:     /{id}/update
    defaults: { _controller: "FormationAdminBundle:Level:update" }
    methods:  [POST, PUT]

level_delete:
    path:     /{id}/delete
    defaults: { _controller: "FormationAdminBundle:Level:delete" }
    methods:  [POST, DELETE]
