subscriptionstatus:
    path:     /
    defaults: { _controller: "FormationAdminBundle:SubscriptionStatus:index" }

subscriptionstatus_show:
    path:     /{id}/show
    defaults: { _controller: "FormationAdminBundle:SubscriptionStatus:show" }

subscriptionstatus_new:
    path:     /new
    defaults: { _controller: "FormationAdminBundle:SubscriptionStatus:new" }

subscriptionstatus_create:
    path:     /create
    defaults: { _controller: "FormationAdminBundle:SubscriptionStatus:create" }
    methods:  POST

subscriptionstatus_edit:
    path:     /{id}/edit
    defaults: { _controller: "FormationAdminBundle:SubscriptionStatus:edit" }

subscriptionstatus_update:
    path:     /{id}/update
    defaults: { _controller: "FormationAdminBundle:SubscriptionStatus:update" }
    methods:  [POST, PUT]

subscriptionstatus_delete:
    path:     /{id}/delete
    defaults: { _controller: "FormationAdminBundle:SubscriptionStatus:delete" }
    methods:  [POST, DELETE]
